kwik/urls.py
from django.conf.urls import patterns, include, url
from views import current_time, tester

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    (r'^',include('people.urls')),
    # (r'^posts/',include('kwiksurfs.urls')),
    (r'^', include('kwiksurfs.urls')),   #, namespace="kwiksurfs")),

    url(r'^$', current_time),
    url(r'^say_hello/$',tester),
    # url(r'^kwik/', include('kwik.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

kwik/people/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_delete
from django.core import urlresolvers
# from django.contrib.contenttypes import generic # for GenericForeignKey

from kwiksurfs.models import Post, NewsCategory #, Picture

# Create your models here.

SEX_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female')
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True, related_name='profile')

    sex = models.CharField(max_length=1, choices=SEX_CHOICES, default="M")
    #picture = models.ForeignKey(Picture) # CamelCase, with an uppercase first letter
    friends = models.ManyToManyField("self") # change this. get rid of the through    # DONE!
    newscategories = models.ManyToManyField(NewsCategory)
    joined_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)    # uncomment, then syncdb
    #active = models.BooleanField(default=False) #after a confirmation mail has been sent and confirmation link clicked, user will be activated
    blocked = models.ManyToManyField(User, related_name='blckd+')

    def __unicode__(self):
        return 'User Profile for: ' + self.user.email

    @models.permalink
    def get_absolute_url(self):
        # return urlresolvers.reverse('view_user', kwargs={'user_id': self.user.id})
        return ('view_user_username', (), {'username': self.user.username})

    def full_name(self):
        return self.user.first_name + " " + self.user.last_name

    def unread_messages_count(self):
        conversations = self.user.conversations.filter(messages__seen=False, users__id__exact=self.user.id).distinct()
        return Message.objects.exclude(sender__id=self.user.id).filter(conversation__in=conversations, seen=False).distinct().count()

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(create_user_profile, sender=User)

class UserVerifier(models.Model):
    user = models.ForeignKey(User, unique=True)
    passcode = models.IntegerField() # random code included in verification link. When verification is completed, model instance is deleted

class FriendshipRequest(models.Model): # throw away this model and create a friendship request model
    initiator = models.ForeignKey(User, related_name='ini+') #are 'related_name's even necessary?
    acceptor = models.ForeignKey(User, related_name='acc+')
    accepted = models.BooleanField(default=False)
    sent_at = models.DateTimeField(auto_now_add=True)
    accepted_at = models.DateTimeField(auto_now=True)

    def get_add_url(self, acceptor_id):
        return urlresolvers.reverse('people.views.add_friend', (), {'acceptor_id': acceptor_id})

    def get_confirm_url(self):
        return urlresolvers.reverse('people.views.confirm_request', (), { 'initiator_id': self.initiator.pk, 'request_id': self.pk, })

    def get_delete_url(self):
        return urlresolvers.reverse('people.views.delete_request', (), { 'initiator_id': self.initiator.pk, 'request_id': self.pk, })

def add_friend_from_request(sender, instance, ** kwargs):    # called when the request is being accepted by the acceptor, just before the request model is deleted
    if instance.accepted:
        the_friend = instance.initiator                          # in this case, the initiator is added to the list of friends of the acceptor
        the_profile = instance.acceptor.get_profile()
        the_profile.friends.add(the_friend)

pre_delete.connect(add_friend_from_request, sender=FriendshipRequest)

class Conversation(models.Model):
    users = models.ManyToManyField(User, related_name="conversations")

    def __unicode__(self):
        return 'Conversation among ' + ", ".join([this_user.get_profile().full_name() for this_user in self.users.all()])

    def get_absolute_url(self):
        #return urlresolvers.reverse('people.views.conversation', (), { 'correspondent_id': self.other_user(user), })       # fix_this!!!
        return urlresolvers.reverse('people.views.conversation_by_id', (), { 'conversation_id': self.id})

    def other_user(self, user):
        for this_user in self.users.all():
            if not this_user == user:
                return this_user

    def unread_messages_count(self, user):
        return self.messages.exclude(sender__id=user.id).filter(seen=False).count()

class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sent', editable=False)
    conversation = models.ForeignKey(Conversation, editable=False, related_name="messages")
    message = models.TextField(default="")
    seen = models.BooleanField(default=False, editable=False)     # I have to add this. For notifying about, and styling new messages
    date_sent = models.DateTimeField(auto_now_add=True, editable=False)   # compulsory!!!

    def __unicode__(self):
        return 'Message from ' + self.sender.username + ' to ' + self.receiver().username

    def receiver(self):
        sender = self.sender
        for user in self.conversation.users.all():
            if not user == sender:
                receiver = user
        return receiver

class UserGroup(models.Model):
    name = models.CharField(max_length=128)
    slug = models.CharField(max_length=128) # do we really need this? we could just use numbers, couldn't we?
    members = models.ManyToManyField(User, related_name='mem+', through='UserGroupMembership')
    admin = models.ForeignKey(User, related_name='ad+')
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return 'Group ' + self.name

class UserGroupMembership(models.Model):
    user = models.ForeignKey(User)
    user_group = models.ForeignKey(UserGroup)
    added = models.BooleanField(default=False) # admin adds and validates requests
    joined_at = models.DateTimeField(auto_now_add=True)

class UserGroupMessage(models.Model):
    sender = models.ForeignKey(User)
    user_group = models.ForeignKey(UserGroup)
    message = models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return 'UserGroupMessage from ' + self.sender + ' to UserGroup ' + self.user_group

kwik/templates/comments.html
<table>
    {% for comment in post.comments.all %}
    <tr>
        <td><a href="{{ comment.author.get_absolute_url }}">{{ comment.author }}</a> said:</td>
        <td>{{ comment.comment }}</td>
        <td>{{ comment.added_at }}</td></tr>
    {% endfor %}
</table>
{% if comment_form %}
<p><b>Add your comment</b></p>
{% if comment_form.errors %}
<p>You made a mistake. Please try again.</p>
{% endif %}
<form method="post" action="{% url add_new_comment post.id %}">
{% csrf_token %}
<table>
{{ comment_form.as_table }}
</table>
<input type="submit" value="send" />
</form>
{% endif %}

kwik/templates/compose-message.html
<html>
<head>
    <title>{{ page_title }}</title>
</head>

{% if form.errors %}
<p>You made a mistake. Please try again.</p>
{% endif %}

<form method="post" action="{% url new_message receiver_id=receiver_id %}">
{% csrf_token %}
<table>
{{ form.as_table }}
</table>
<input type="submit" value="send" />
</form>
</html>

kwik/templates/confirm-delete-request.html
<html>
<head>
    <title>{{ page_title }}</title>
</head>

{% if form.errors %}
<p>You made a mistake. Please try again.</p>
{% endif %}

<form method="post" action="{% url delete_request request_id=request_id initiator_id=initiator_id %}">
{% csrf_token %}
<table>
<input type="hidden" name="request_id" value="{{ request_id }}" />
</table>
<input type="submit" value="confirm" />
</form>
</html>

kwik/templates/conversation.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{{ page_title }}</title>
</head>
<body>
<h1>{{ page_title }}</h1>

<p><b>New Message</b></p>
{% if form.errors %}
<p>You made a mistake. Please try again.</p>
{% endif %}
<form method="post" action="{% url conversation correspondent_id=correspondent_id %}">
{% csrf_token %}
<table>
{{ form.as_table }}
</table>
<input type="submit" value="send" />
</form>

<table>
    {% for message in messages %}
    <tr>
        <td>From <a href="{{ message.sender.get_absolute_url }}">{{ message.sender }}</a></td>
        <td>To <a href="{{ message.receiver.get_absolute_url }}">{{ message.receiver }}</a></td>
        <td>{{ message.message }}</td>
        <td>Sent on: {{ message.date_sent }}</td>
        <td>Read: {{ message.seen }} | {% if message.seen %}Y{% else %}N{% endif %}</td>
    </tr>
    {% endfor %}
</table>
</body>
</html>

kwik/templates/conversations.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{{ page_title }}</title>
</head>
<body>
<h1>{{ page_title }}</h1>
<table>
    {% for conversation in conversations %}
    <tr>{% comment %} change this to "conversation between you and <a href>somebody</a>"{% endcomment %}
        <td>Conversation among {% for each_user in conversation.users.all %}<a href="{% url view_user user_id=each_user.id %}">{{ each_user.get_profile.full_name }}</a> - {% endfor %}</td>
        <td><a href="{% url conversation_by_id conversation_id=conversation.id %}">view</a></td>
        <td>{{ conversation.message_count }} messages</td>
    </tr>
    {% endfor %}
</table>
</body>
</html>

kwik/templates/login.html
<html>
<head>
    <title>{{ page_title }}</title>
</head>

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action=".">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>
</html>

kwik/templates/posts.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{{ page_title }}</title>
</head>
<body>
<h1>{{ page_title }}</h1>
{% if form %}
<p><b>New Post</b></p>
{% if form.errors %}
<p>You made a mistake. Please try again.</p>
{% endif %}
<form method="post" action="{% url new_post %}">
{% csrf_token %}
<table>
{{ form.as_table }}
</table>
<input type="submit" value="send" />
</form>
{% endif %}
<table>
    {% for post in posts %}
    <tr>
        <td><a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a> said:</td>
    </tr>
        <tr><td>{{ post.post }}</td></tr>
        <tr><td>{{ post.added_at }}</td></tr>
    <tr>
        <td>
            <blockquote>
                {% include "comments.html" %}
            </blockquote>
        </td>
    </tr>
    {% endfor %}
</table>
</body>
</html>

kwik/templates/profile-form.html
<html>
<head>
    <title>{{ page_title }}</title>
</head>

{% if form.errors %}
<p>You made a mistake. Please try again.</p>
{% endif %}

<form method="post" action="{% url edit_profile %}">
{% csrf_token %}
<table>
{{ form.as_table }}
</table>
<table>
{{ user_form.as_table }}
</table>
<input type="submit" value="save" />
<input type="hidden" name="next" value="{{ next }}" />
</form>
</html>

kwik/templates/profile.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{{ page_title }}</title>
</head>
<body>
<p><a href="{% url all_users %}">All Users</a></p>
<h1>{{ page_title }}</h1>
<p>{% if message %}{{ message }}{% endif %}</p>
{% if user.is_authenticated %}
<p>{% if page_title = "My Profile" %}
        <a href="{% url edit_profile %}">Edit</a>
        You have {{ user_profile.unread_messages_count }} new message{{ user_profile.unread_messages_count|pluralize }}.<a href="{% url conversations %}">View</a>
    {% endif %}
    {% if user.id != this_user.id %}
        {% if user in friends_list  %}Friends
        {% else %}
            {% if request_sent = "to" %}
                Awaiting request confirmation
            {% elif request_sent = "from" %}
                <a href="{{ friendship_request.get_confirm_url }}">Confirm Friend</a> | <a href="{{ friendship_request.get_delete_url }}">Delete Request</a>
            {% elif request_sent = 0 %}
                <a href="{% url add_friend user_id %}">Add Friend</a>
            {% endif %}
        {% endif %}
    {% endif %}</p>
<p><a href="{% url view_requests %}">View Friendship Requests</a></p>
{% endif %}
<table>
    {% if not this_user = user %}
    <tr>
        <td><a href="{% url new_message receiver_id=this_user.id %}">Message</a></td>
    </tr>
    {% endif %}
    <tr>
        <td>Username:</td><td>{{ this_user.username }}</td>
    </tr>
    <tr>
        <td>First Name:</td><td>{{ this_user.first_name }}</td>
    </tr>
    <tr>
        <td>Last Name:</td><td>{{ this_user.last_name }}</td>
    </tr>
    <tr>
        <td>Email Address:</td><td>{{ this_user.email }}</td>
    </tr>
    <tr>
        <td>Friends:</td>
        <td>
            {% for friend in friends_list %}
                <li><a href="{{ friend.get_absolute_url }}">{{ friend.user.first_name }} {{ friend.user.last_name }}</a></li>
            {% endfor %}
        </td>
    </tr>
    <tr>
        <td>Sex:</td>
        <td>{{ this_user_profile.sex }}</td>
    </tr>
</table>
</body>
</html>

kwik/templates/register.html
<html>
<head>
    <title>{{ page_title }}</title>
</head>

{% if form.errors %}
<p>You made a mistake. Please try again.</p>
{% endif %}

<form method="post" action=".">
{% csrf_token %}
<table>
{{ form.as_table }}
{% comment %}
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
{% endcomment %}
</table>
<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>
</html>

kwik/templates/requests.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{{ page_title }}</title>
</head>
<body>
<h1>{{ page_title }}</h1>
<p>{% if message %}{{ message }}{% endif %}</p>
<table>
    {% for request in requests %}
    <tr>
        <td>From <a href="{% url view_user user_id=request.initiator.id %}">{{ request.initiator }}</a></td>
        <td><a href="{% url confirm_request request_id=request.id initiator_id=request.initiator.id %}">Confirm</a></td>
        <td><a href="{% url delete_request request_id=request.id initiator_id=request.initiator.id %}">Delete</a></td>
    </tr>
    {% empty %}
    <tr><td>No Friend Requests!!!</td></tr>
    {% endfor %}
</table>
</body>
</html>

kwik/templates/users_list.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{{ page_title }}</title>
</head>
<body>
<h1>{{ page_title }}</h1>
<table border="1">
    {% for this_user in users %}
    <tr>
        <td>{{ this_user.first_name }} {{ this_user.last_name }}</td>
        <td><a href="{% url view_user this_user.id %}">View User</a></td>
        <td>{% if this_user.get_profile in user_profile.friends.all %}Friend{% else %}Not Friend{% endif %}</td>
        <td>{{ this_user.username }}</td>
        <td>{{ this_user.get_profile.get_sex_display }}</td>
        <td>{{ this_user.email }}</td>
    </tr>
    {% endfor %}
</table>
</body>
</html>